### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by ghost** [nift4/NoDeviceCheckReborn#3]

**Comment by nift4** [comment]
i know, this is like really old and useless

**Comment by ghost** [comment]
![Screenshot_۲۰۲۲۰۱۳۰-۱۶۲۶۳۱](https://user-images.githubusercontent.com/90418723/151700637-d8306a09-05de-4c21-adc0-d82d1c14ee4f.png)
Is there no other way?🙁

**Comment by nift4** [comment]
there are many ways but this is not one of them
